name: Generate Pac-Man Contribution Graph

on:
  schedule:
    # Run every 24 hours at midnight UTC
    - cron: "0 0 * * *"
  
  # Allows manually triggering the workflow from GitHub Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman contribution graph svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RifqiAqil-ops
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push contribution graph svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
